WARNING: The 'agent' command group has been deprecated. It will not be available after Sep 2024. Use `prefect worker start` instead. Refer to the upgrade guide for more information: https://docs.prefect.io/latest/guides/upgrade-guide-agents-to-workers/.
Starting v2.18.0 agent connected to 
https://api.prefect.cloud/api/accounts/38fbb916-4b5e-4677-b2d1-1b1684e2301f/work
spaces/2b5b2172-396a-4913-8639-e986423bbc27...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from work pool 'default-agent-pool'...
22:22:51.153 | INFO    | prefect.agent - Found 1 flow runs awaiting cancellation.
22:22:52.023 | INFO    | prefect.agent - Killing process huythai-213:335309 for flow run 'c82e2387-ce87-4313-8af8-4c493fd45850'...
22:22:52.034 | WARNING | prefect.agent - Unable to kill process 335309: The process was not found. Marking flow run as cancelled.
22:23:46.285 | INFO    | prefect.agent - Submitting flow run 'c7981ac8-237a-46a4-bc24-3c795745185a'
22:23:47.583 | INFO    | prefect.infrastructure.process - Opening process 'cooperative-leopard'...
22:23:47.914 | INFO    | prefect.agent - Completed submission of flow run 'c7981ac8-237a-46a4-bc24-3c795745185a'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
22:23:51.218 | INFO    | Flow run 'cooperative-leopard' - Downloading flow code from storage at '/home/huythai/final/test_producer'
22:23:53.119 | INFO    | Flow run 'cooperative-leopard' - Created task run 'collect_data-0' for task 'collect_data'
22:23:53.124 | INFO    | Flow run 'cooperative-leopard' - Executing 'collect_data-0' immediately...
22:27:52.120 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
22:27:52.438 | INFO    | Flow run 'cooperative-leopard' - Created task run 'transform_data-0' for task 'transform_data'
22:27:52.441 | INFO    | Flow run 'cooperative-leopard' - Executing 'transform_data-0' immediately...
22:27:53.305 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
22:27:53.600 | INFO    | Flow run 'cooperative-leopard' - Created task run 'load_data-0' for task 'load_data'
22:27:53.602 | INFO    | Flow run 'cooperative-leopard' - Executing 'load_data-0' immediately...
22:27:54.459 | INFO    | Task run 'load_data-0' - Finished in state Completed()
22:27:54.781 | INFO    | Flow run 'cooperative-leopard' - Finished in state Completed('All states completed.')
1611
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol ROS: local variable 'df' referenced before assignment
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol TKC: local variable 'df' referenced before assignment
22:27:57.857 | INFO    | prefect.infrastructure.process - Process 'cooperative-leopard' exited cleanly.
22:36:28.373 | INFO    | prefect.agent - Submitting flow run 'a98cc0ce-cbc4-4fc9-9c69-a883e690eb1d'
22:36:29.536 | INFO    | prefect.infrastructure.process - Opening process 'colorful-bettong'...
22:36:29.919 | INFO    | prefect.agent - Completed submission of flow run 'a98cc0ce-cbc4-4fc9-9c69-a883e690eb1d'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
22:36:33.726 | INFO    | Flow run 'colorful-bettong' - Downloading flow code from storage at '/home/huythai/final/test_producer'
22:36:35.852 | INFO    | Flow run 'colorful-bettong' - Created task run 'collect_data-0' for task 'collect_data'
22:36:35.855 | INFO    | Flow run 'colorful-bettong' - Executing 'collect_data-0' immediately...
22:41:06.240 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
22:41:06.570 | INFO    | Flow run 'colorful-bettong' - Created task run 'transform_data-0' for task 'transform_data'
22:41:06.571 | INFO    | Flow run 'colorful-bettong' - Executing 'transform_data-0' immediately...
22:41:07.457 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
22:41:07.771 | INFO    | Flow run 'colorful-bettong' - Created task run 'load_data-0' for task 'load_data'
22:41:07.773 | INFO    | Flow run 'colorful-bettong' - Executing 'load_data-0' immediately...
22:41:08.660 | INFO    | Task run 'load_data-0' - Finished in state Completed()
22:41:08.987 | INFO    | Flow run 'colorful-bettong' - Finished in state Completed('All states completed.')
1611
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol ROS: local variable 'df' referenced before assignment
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol TKC: local variable 'df' referenced before assignment
22:41:12.165 | INFO    | prefect.infrastructure.process - Process 'colorful-bettong' exited cleanly.
22:47:55.936 | INFO    | prefect.agent - Submitting flow run '33560224-f46b-4ee9-9e53-3388f06d0fe8'
22:47:57.182 | INFO    | prefect.infrastructure.process - Opening process 'pumpkin-ape'...
22:47:57.485 | INFO    | prefect.agent - Completed submission of flow run '33560224-f46b-4ee9-9e53-3388f06d0fe8'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
22:48:01.138 | INFO    | Flow run 'pumpkin-ape' - Downloading flow code from storage at '/home/huythai/final/test_producer'
22:48:03.063 | INFO    | Flow run 'pumpkin-ape' - Created task run 'collect_data-0' for task 'collect_data'
22:48:03.067 | INFO    | Flow run 'pumpkin-ape' - Executing 'collect_data-0' immediately...
22:52:09.986 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
22:52:10.289 | INFO    | Flow run 'pumpkin-ape' - Created task run 'transform_data-0' for task 'transform_data'
22:52:10.290 | INFO    | Flow run 'pumpkin-ape' - Executing 'transform_data-0' immediately...
22:52:11.153 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
22:52:11.461 | INFO    | Flow run 'pumpkin-ape' - Created task run 'load_data-0' for task 'load_data'
22:52:11.463 | INFO    | Flow run 'pumpkin-ape' - Executing 'load_data-0' immediately...
22:52:12.330 | INFO    | Task run 'load_data-0' - Finished in state Completed()
22:52:12.654 | INFO    | Flow run 'pumpkin-ape' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol ROS: local variable 'df' referenced before assignment
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol TKC: local variable 'df' referenced before assignment
22:52:15.782 | INFO    | prefect.infrastructure.process - Process 'pumpkin-ape' exited cleanly.
22:55:57.429 | INFO    | prefect.agent - Submitting flow run 'a98cc0ce-cbc4-4fc9-9c69-a883e690eb1d'
22:55:58.545 | INFO    | prefect.infrastructure.process - Opening process 'colorful-bettong'...
22:55:58.860 | INFO    | prefect.agent - Completed submission of flow run 'a98cc0ce-cbc4-4fc9-9c69-a883e690eb1d'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
22:56:02.286 | INFO    | Flow run 'colorful-bettong' - Downloading flow code from storage at '/home/huythai/final/test_producer'
22:56:04.092 | INFO    | Flow run 'colorful-bettong' - Created task run 'collect_data-0' for task 'collect_data'
22:56:04.096 | INFO    | Flow run 'colorful-bettong' - Executing 'collect_data-0' immediately...
23:00:30.480 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
23:00:30.802 | INFO    | Flow run 'colorful-bettong' - Created task run 'transform_data-0' for task 'transform_data'
23:00:30.803 | INFO    | Flow run 'colorful-bettong' - Executing 'transform_data-0' immediately...
23:00:31.777 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
23:00:32.092 | INFO    | Flow run 'colorful-bettong' - Created task run 'load_data-0' for task 'load_data'
23:00:32.093 | INFO    | Flow run 'colorful-bettong' - Executing 'load_data-0' immediately...
23:00:32.991 | INFO    | Task run 'load_data-0' - Finished in state Completed()
23:00:33.345 | INFO    | Flow run 'colorful-bettong' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol ROS: local variable 'df' referenced before assignment
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error processing stock symbol TKC: local variable 'df' referenced before assignment
23:00:36.783 | INFO    | prefect.infrastructure.process - Process 'colorful-bettong' exited cleanly.
08:59:50.384 | INFO    | prefect.agent - Submitting flow run '27b974a3-7478-463e-81ee-f5999700ef28'
08:59:52.497 | INFO    | prefect.infrastructure.process - Opening process 'dandelion-horse'...
08:59:52.847 | INFO    | prefect.agent - Completed submission of flow run '27b974a3-7478-463e-81ee-f5999700ef28'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
08:59:57.810 | INFO    | Flow run 'dandelion-horse' - Downloading flow code from storage at '/home/huythai/final/test_producer'
09:00:00.515 | INFO    | Flow run 'dandelion-horse' - Created task run 'collect_data-0' for task 'collect_data'
09:00:00.517 | INFO    | Flow run 'dandelion-horse' - Executing 'collect_data-0' immediately...
09:00:24.198 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
09:00:25.403 | INFO    | Flow run 'dandelion-horse' - Created task run 'transform_data-0' for task 'transform_data'
09:00:25.405 | INFO    | Flow run 'dandelion-horse' - Executing 'transform_data-0' immediately...
09:00:26.875 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
09:00:27.177 | INFO    | Flow run 'dandelion-horse' - Created task run 'load_data-0' for task 'load_data'
09:00:27.179 | INFO    | Flow run 'dandelion-horse' - Executing 'load_data-0' immediately...
09:00:30.024 | INFO    | Task run 'load_data-0' - Finished in state Completed()
09:00:30.382 | INFO    | Flow run 'dandelion-horse' - Finished in state Completed('All states completed.')
09:00:33.689 | INFO    | prefect.infrastructure.process - Process 'dandelion-horse' exited cleanly.
09:14:52.794 | INFO    | prefect.agent - Submitting flow run '7db060a7-fbcd-4ee8-9d13-8b3e3946d18e'
09:14:53.940 | INFO    | prefect.infrastructure.process - Opening process 'belligerent-dogfish'...
09:14:54.286 | INFO    | prefect.agent - Completed submission of flow run '7db060a7-fbcd-4ee8-9d13-8b3e3946d18e'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
09:14:58.068 | INFO    | Flow run 'belligerent-dogfish' - Downloading flow code from storage at '/home/huythai/final/test_producer'
09:15:01.343 | INFO    | Flow run 'belligerent-dogfish' - Created task run 'collect_data-0' for task 'collect_data'
09:15:01.345 | INFO    | Flow run 'belligerent-dogfish' - Executing 'collect_data-0' immediately...
09:15:20.135 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
09:15:20.493 | INFO    | Flow run 'belligerent-dogfish' - Created task run 'transform_data-0' for task 'transform_data'
09:15:20.495 | INFO    | Flow run 'belligerent-dogfish' - Executing 'transform_data-0' immediately...
09:15:21.397 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
09:15:21.706 | INFO    | Flow run 'belligerent-dogfish' - Created task run 'load_data-0' for task 'load_data'
09:15:21.707 | INFO    | Flow run 'belligerent-dogfish' - Executing 'load_data-0' immediately...
09:15:22.609 | INFO    | Task run 'load_data-0' - Finished in state Completed()
09:15:22.939 | INFO    | Flow run 'belligerent-dogfish' - Finished in state Completed('All states completed.')
09:15:26.193 | INFO    | prefect.infrastructure.process - Process 'belligerent-dogfish' exited cleanly.
09:30:03.623 | INFO    | prefect.agent - Submitting flow run '2494223a-5a24-4079-b425-7a63f18a6a4b'
09:30:06.697 | INFO    | prefect.infrastructure.process - Opening process 'warm-marten'...
09:30:07.120 | INFO    | prefect.agent - Completed submission of flow run '2494223a-5a24-4079-b425-7a63f18a6a4b'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
09:30:10.337 | INFO    | Flow run 'warm-marten' - Downloading flow code from storage at '/home/huythai/final/test_producer'
09:30:12.543 | INFO    | Flow run 'warm-marten' - Created task run 'collect_data-0' for task 'collect_data'
09:30:12.546 | INFO    | Flow run 'warm-marten' - Executing 'collect_data-0' immediately...
09:30:25.714 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
09:30:26.038 | INFO    | Flow run 'warm-marten' - Created task run 'transform_data-0' for task 'transform_data'
09:30:26.040 | INFO    | Flow run 'warm-marten' - Executing 'transform_data-0' immediately...
09:30:26.990 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
09:30:27.293 | INFO    | Flow run 'warm-marten' - Created task run 'load_data-0' for task 'load_data'
09:30:27.295 | INFO    | Flow run 'warm-marten' - Executing 'load_data-0' immediately...
09:30:28.253 | INFO    | Task run 'load_data-0' - Finished in state Completed()
09:30:28.592 | INFO    | Flow run 'warm-marten' - Finished in state Completed('All states completed.')
09:30:31.491 | INFO    | prefect.infrastructure.process - Process 'warm-marten' exited cleanly.
10:14:56.524 | INFO    | prefect.agent - Submitting flow run 'ed5fa0a5-4325-4786-8718-760085c8eb61'
10:14:57.680 | INFO    | prefect.infrastructure.process - Opening process 'pink-mink'...
10:14:58.426 | INFO    | prefect.agent - Completed submission of flow run 'ed5fa0a5-4325-4786-8718-760085c8eb61'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
10:15:01.520 | INFO    | Flow run 'pink-mink' - Downloading flow code from storage at '/home/huythai/final/test_producer'
10:15:03.715 | INFO    | Flow run 'pink-mink' - Created task run 'collect_data-0' for task 'collect_data'
10:15:03.719 | INFO    | Flow run 'pink-mink' - Executing 'collect_data-0' immediately...
10:15:54.742 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
10:17:21.192 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
10:17:58.748 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
10:17:59.052 | INFO    | Flow run 'pink-mink' - Created task run 'transform_data-0' for task 'transform_data'
10:17:59.053 | INFO    | Flow run 'pink-mink' - Executing 'transform_data-0' immediately...
10:17:59.960 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
10:18:00.264 | INFO    | Flow run 'pink-mink' - Created task run 'load_data-0' for task 'load_data'
10:18:00.265 | INFO    | Flow run 'pink-mink' - Executing 'load_data-0' immediately...
10:18:01.189 | INFO    | Task run 'load_data-0' - Finished in state Completed()
10:18:01.511 | INFO    | Flow run 'pink-mink' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

10:18:04.695 | INFO    | prefect.infrastructure.process - Process 'pink-mink' exited cleanly.
10:29:54.012 | INFO    | prefect.agent - Submitting flow run 'd6022b28-8c50-4409-b68f-40debb86da5d'
10:29:55.141 | INFO    | prefect.infrastructure.process - Opening process 'mighty-weasel'...
10:29:55.468 | INFO    | prefect.agent - Completed submission of flow run 'd6022b28-8c50-4409-b68f-40debb86da5d'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
10:29:58.731 | INFO    | Flow run 'mighty-weasel' - Downloading flow code from storage at '/home/huythai/final/test_producer'
10:30:00.626 | INFO    | Flow run 'mighty-weasel' - Created task run 'collect_data-0' for task 'collect_data'
10:30:00.628 | INFO    | Flow run 'mighty-weasel' - Executing 'collect_data-0' immediately...
10:30:42.876 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
10:32:13.285 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
10:32:44.016 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
10:32:44.341 | INFO    | Flow run 'mighty-weasel' - Created task run 'transform_data-0' for task 'transform_data'
10:32:44.344 | INFO    | Flow run 'mighty-weasel' - Executing 'transform_data-0' immediately...
10:32:45.262 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
10:32:45.578 | INFO    | Flow run 'mighty-weasel' - Created task run 'load_data-0' for task 'load_data'
10:32:45.580 | INFO    | Flow run 'mighty-weasel' - Executing 'load_data-0' immediately...
10:32:48.981 | INFO    | Task run 'load_data-0' - Finished in state Completed()
10:32:49.320 | INFO    | Flow run 'mighty-weasel' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

10:32:52.514 | INFO    | prefect.infrastructure.process - Process 'mighty-weasel' exited cleanly.
10:44:54.812 | INFO    | prefect.agent - Submitting flow run '82385262-5c7e-4144-8bdf-e5284ca785ae'
10:44:56.337 | INFO    | prefect.infrastructure.process - Opening process 'ultra-herring'...
10:44:56.668 | INFO    | prefect.agent - Completed submission of flow run '82385262-5c7e-4144-8bdf-e5284ca785ae'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
10:45:00.364 | INFO    | Flow run 'ultra-herring' - Downloading flow code from storage at '/home/huythai/final/test_producer'
10:45:02.344 | INFO    | Flow run 'ultra-herring' - Created task run 'collect_data-0' for task 'collect_data'
10:45:02.345 | INFO    | Flow run 'ultra-herring' - Executing 'collect_data-0' immediately...
10:45:47.618 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
10:47:08.975 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
10:47:36.752 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
10:47:37.062 | INFO    | Flow run 'ultra-herring' - Created task run 'transform_data-0' for task 'transform_data'
10:47:37.064 | INFO    | Flow run 'ultra-herring' - Executing 'transform_data-0' immediately...
10:47:37.969 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
10:47:38.270 | INFO    | Flow run 'ultra-herring' - Created task run 'load_data-0' for task 'load_data'
10:47:38.272 | INFO    | Flow run 'ultra-herring' - Executing 'load_data-0' immediately...
10:47:39.172 | INFO    | Task run 'load_data-0' - Finished in state Completed()
10:47:39.498 | INFO    | Flow run 'ultra-herring' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

10:47:42.634 | INFO    | prefect.infrastructure.process - Process 'ultra-herring' exited cleanly.
11:00:00.255 | INFO    | prefect.agent - Submitting flow run '0f09f6c3-25d9-455c-90a0-795e8b169d40'
11:00:02.620 | INFO    | prefect.infrastructure.process - Opening process 'arcane-mandrill'...
11:00:02.948 | INFO    | prefect.agent - Completed submission of flow run '0f09f6c3-25d9-455c-90a0-795e8b169d40'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
11:00:07.111 | INFO    | Flow run 'arcane-mandrill' - Downloading flow code from storage at '/home/huythai/final/test_producer'
11:00:11.114 | INFO    | Flow run 'arcane-mandrill' - Created task run 'collect_data-0' for task 'collect_data'
11:00:11.117 | INFO    | Flow run 'arcane-mandrill' - Executing 'collect_data-0' immediately...
11:00:57.083 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
11:02:31.602 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
11:03:11.378 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
11:03:11.703 | INFO    | Flow run 'arcane-mandrill' - Created task run 'transform_data-0' for task 'transform_data'
11:03:11.705 | INFO    | Flow run 'arcane-mandrill' - Executing 'transform_data-0' immediately...
11:03:12.668 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
11:03:12.982 | INFO    | Flow run 'arcane-mandrill' - Created task run 'load_data-0' for task 'load_data'
11:03:12.985 | INFO    | Flow run 'arcane-mandrill' - Executing 'load_data-0' immediately...
11:03:13.893 | INFO    | Task run 'load_data-0' - Finished in state Completed()
11:03:14.255 | INFO    | Flow run 'arcane-mandrill' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

11:03:17.545 | INFO    | prefect.infrastructure.process - Process 'arcane-mandrill' exited cleanly.
11:14:48.456 | INFO    | prefect.agent - Submitting flow run '2ad7bfbe-403b-4c9d-9d4e-7ff140f09ef8'
11:14:49.633 | INFO    | prefect.infrastructure.process - Opening process 'lavender-jackal'...
11:14:49.933 | INFO    | prefect.agent - Completed submission of flow run '2ad7bfbe-403b-4c9d-9d4e-7ff140f09ef8'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
11:14:53.585 | INFO    | Flow run 'lavender-jackal' - Downloading flow code from storage at '/home/huythai/final/test_producer'
11:15:00.797 | INFO    | Flow run 'lavender-jackal' - Created task run 'collect_data-0' for task 'collect_data'
11:15:00.799 | INFO    | Flow run 'lavender-jackal' - Executing 'collect_data-0' immediately...
11:15:40.124 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
11:16:57.732 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
11:17:28.921 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
11:17:29.248 | INFO    | Flow run 'lavender-jackal' - Created task run 'transform_data-0' for task 'transform_data'
11:17:29.250 | INFO    | Flow run 'lavender-jackal' - Executing 'transform_data-0' immediately...
11:17:30.161 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
11:17:30.482 | INFO    | Flow run 'lavender-jackal' - Created task run 'load_data-0' for task 'load_data'
11:17:30.484 | INFO    | Flow run 'lavender-jackal' - Executing 'load_data-0' immediately...
11:17:33.923 | INFO    | Task run 'load_data-0' - Finished in state Completed()
11:17:34.254 | INFO    | Flow run 'lavender-jackal' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

11:17:37.166 | INFO    | prefect.infrastructure.process - Process 'lavender-jackal' exited cleanly.
11:29:53.149 | INFO    | prefect.agent - Submitting flow run '11b32000-4dc1-4da2-92fa-f8cc75ccc077'
11:29:54.321 | INFO    | prefect.infrastructure.process - Opening process 'pistachio-buzzard'...
11:29:54.649 | INFO    | prefect.agent - Completed submission of flow run '11b32000-4dc1-4da2-92fa-f8cc75ccc077'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
11:29:57.966 | INFO    | Flow run 'pistachio-buzzard' - Downloading flow code from storage at '/home/huythai/final/test_producer'
11:30:01.143 | INFO    | Flow run 'pistachio-buzzard' - Created task run 'collect_data-0' for task 'collect_data'
11:30:01.145 | INFO    | Flow run 'pistachio-buzzard' - Executing 'collect_data-0' immediately...
11:30:44.832 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
11:32:11.516 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
11:32:44.225 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
11:32:44.555 | INFO    | Flow run 'pistachio-buzzard' - Created task run 'transform_data-0' for task 'transform_data'
11:32:44.557 | INFO    | Flow run 'pistachio-buzzard' - Executing 'transform_data-0' immediately...
11:32:45.518 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
11:32:45.827 | INFO    | Flow run 'pistachio-buzzard' - Created task run 'load_data-0' for task 'load_data'
11:32:45.830 | INFO    | Flow run 'pistachio-buzzard' - Executing 'load_data-0' immediately...
11:32:47.226 | INFO    | Task run 'load_data-0' - Finished in state Completed()
11:32:47.546 | INFO    | Flow run 'pistachio-buzzard' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

11:32:50.513 | INFO    | prefect.infrastructure.process - Process 'pistachio-buzzard' exited cleanly.
11:44:56.802 | INFO    | prefect.agent - Submitting flow run '79768dcb-ade1-4e3a-99c3-c2acb4d656af'
11:44:58.004 | INFO    | prefect.infrastructure.process - Opening process 'dark-lemming'...
11:44:58.338 | INFO    | prefect.agent - Completed submission of flow run '79768dcb-ade1-4e3a-99c3-c2acb4d656af'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
11:45:01.764 | INFO    | Flow run 'dark-lemming' - Downloading flow code from storage at '/home/huythai/final/test_producer'
11:45:03.770 | INFO    | Flow run 'dark-lemming' - Created task run 'collect_data-0' for task 'collect_data'
11:45:03.772 | INFO    | Flow run 'dark-lemming' - Executing 'collect_data-0' immediately...
11:45:42.154 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
11:47:13.277 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
11:47:40.681 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
11:47:40.982 | INFO    | Flow run 'dark-lemming' - Created task run 'transform_data-0' for task 'transform_data'
11:47:40.984 | INFO    | Flow run 'dark-lemming' - Executing 'transform_data-0' immediately...
11:47:41.878 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
11:47:42.181 | INFO    | Flow run 'dark-lemming' - Created task run 'load_data-0' for task 'load_data'
11:47:42.183 | INFO    | Flow run 'dark-lemming' - Executing 'load_data-0' immediately...
11:47:43.057 | INFO    | Task run 'load_data-0' - Finished in state Completed()
11:47:43.395 | INFO    | Flow run 'dark-lemming' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

11:47:46.342 | INFO    | prefect.infrastructure.process - Process 'dark-lemming' exited cleanly.
11:59:55.004 | INFO    | prefect.agent - Submitting flow run '2b955ba0-846a-49a1-bc48-62791974def1'
11:59:56.632 | INFO    | prefect.infrastructure.process - Opening process 'nebulous-butterfly'...
11:59:56.995 | INFO    | prefect.agent - Completed submission of flow run '2b955ba0-846a-49a1-bc48-62791974def1'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
12:00:02.031 | INFO    | Flow run 'nebulous-butterfly' - Downloading flow code from storage at '/home/huythai/final/test_producer'
12:00:04.427 | INFO    | Flow run 'nebulous-butterfly' - Created task run 'collect_data-0' for task 'collect_data'
12:00:04.428 | INFO    | Flow run 'nebulous-butterfly' - Executing 'collect_data-0' immediately...
12:00:48.242 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
12:02:24.616 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
12:02:59.710 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
12:03:00.027 | INFO    | Flow run 'nebulous-butterfly' - Created task run 'transform_data-0' for task 'transform_data'
12:03:00.028 | INFO    | Flow run 'nebulous-butterfly' - Executing 'transform_data-0' immediately...
12:03:01.117 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
12:03:01.434 | INFO    | Flow run 'nebulous-butterfly' - Created task run 'load_data-0' for task 'load_data'
12:03:01.436 | INFO    | Flow run 'nebulous-butterfly' - Executing 'load_data-0' immediately...
12:03:02.354 | INFO    | Task run 'load_data-0' - Finished in state Completed()
12:03:02.699 | INFO    | Flow run 'nebulous-butterfly' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

12:03:05.883 | INFO    | prefect.infrastructure.process - Process 'nebulous-butterfly' exited cleanly.
12:14:50.041 | INFO    | prefect.agent - Submitting flow run '806039c9-95be-4bda-83fb-bfbe11159dde'
12:14:51.274 | INFO    | prefect.infrastructure.process - Opening process 'fluffy-mackerel'...
12:14:51.592 | INFO    | prefect.agent - Completed submission of flow run '806039c9-95be-4bda-83fb-bfbe11159dde'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
12:14:54.954 | INFO    | Flow run 'fluffy-mackerel' - Downloading flow code from storage at '/home/huythai/final/test_producer'
12:15:01.196 | INFO    | Flow run 'fluffy-mackerel' - Created task run 'collect_data-0' for task 'collect_data'
12:15:01.198 | INFO    | Flow run 'fluffy-mackerel' - Executing 'collect_data-0' immediately...
12:15:39.554 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
12:17:07.032 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
12:17:36.221 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
12:17:36.523 | INFO    | Flow run 'fluffy-mackerel' - Created task run 'transform_data-0' for task 'transform_data'
12:17:36.525 | INFO    | Flow run 'fluffy-mackerel' - Executing 'transform_data-0' immediately...
12:17:37.405 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
12:17:37.704 | INFO    | Flow run 'fluffy-mackerel' - Created task run 'load_data-0' for task 'load_data'
12:17:37.705 | INFO    | Flow run 'fluffy-mackerel' - Executing 'load_data-0' immediately...
12:17:38.996 | INFO    | Task run 'load_data-0' - Finished in state Completed()
12:17:39.316 | INFO    | Flow run 'fluffy-mackerel' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

12:17:42.332 | INFO    | prefect.infrastructure.process - Process 'fluffy-mackerel' exited cleanly.
12:29:57.654 | INFO    | prefect.agent - Submitting flow run 'dde7df83-5477-4294-848a-c2caa6df7666'
12:29:58.846 | INFO    | prefect.infrastructure.process - Opening process 'khaki-oyster'...
12:29:59.176 | INFO    | prefect.agent - Completed submission of flow run 'dde7df83-5477-4294-848a-c2caa6df7666'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
12:30:04.379 | INFO    | Flow run 'khaki-oyster' - Downloading flow code from storage at '/home/huythai/final/test_producer'
12:30:07.728 | INFO    | Flow run 'khaki-oyster' - Created task run 'collect_data-0' for task 'collect_data'
12:30:07.731 | INFO    | Flow run 'khaki-oyster' - Executing 'collect_data-0' immediately...
12:30:08.562 | ERROR   | Task run 'collect_data-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 2099, in orchestrate_task_run
    result = await call.aresult()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp2ljqhbgoprefect/producer.py", line 77, in collect_data
    data= list(pool.map(retrieve_real_time_data,divide_list(stock_symbols,num_of_thread)))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp2ljqhbgoprefect/producer.py", line 52, in retrieve_real_time_data
    logger=get_run_logger()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/logging/loggers.py", line 155, in get_run_logger
    raise MissingContextError("There is no active flow or task run context.")
prefect.exceptions.MissingContextError: There is no active flow or task run context.
12:30:08.884 | ERROR   | Task run 'collect_data-0' - Finished in state Failed('Task run encountered an exception MissingContextError: There is no active flow or task run context.')
12:30:08.899 | ERROR   | Flow run 'khaki-oyster' - Encountered exception during execution:
Traceback (most recent call last):
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 875, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp2ljqhbgoprefect/producer.py", line 103, in main
    data=collect_data()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/tasks.py", line 600, in __call__
    return enter_task_run_engine(
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 1417, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 1551, in get_task_call_return_value
    return await future._result()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 2099, in orchestrate_task_run
    result = await call.aresult()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp2ljqhbgoprefect/producer.py", line 77, in collect_data
    data= list(pool.map(retrieve_real_time_data,divide_list(stock_symbols,num_of_thread)))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp2ljqhbgoprefect/producer.py", line 52, in retrieve_real_time_data
    logger=get_run_logger()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/logging/loggers.py", line 155, in get_run_logger
    raise MissingContextError("There is no active flow or task run context.")
prefect.exceptions.MissingContextError: There is no active flow or task run context.
12:30:09.266 | ERROR   | Flow run 'khaki-oyster' - Finished in state Failed('Flow run encountered an exception. MissingContextError: There is no active flow or task run context.')
12:30:12.551 | INFO    | prefect.infrastructure.process - Process 'khaki-oyster' exited cleanly.
12:33:32.684 | INFO    | prefect.agent - Submitting flow run '61411228-67e6-4734-86ad-e31566ed83d6'
12:33:33.849 | INFO    | prefect.infrastructure.process - Opening process 'defiant-harrier'...
12:33:34.160 | INFO    | prefect.agent - Completed submission of flow run '61411228-67e6-4734-86ad-e31566ed83d6'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
12:33:37.433 | INFO    | Flow run 'defiant-harrier' - Downloading flow code from storage at '/home/huythai/final/test_producer'
12:33:39.240 | INFO    | Flow run 'defiant-harrier' - Created task run 'collect_data-0' for task 'collect_data'
12:33:39.242 | INFO    | Flow run 'defiant-harrier' - Executing 'collect_data-0' immediately...
12:33:40.106 | ERROR   | Task run 'collect_data-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 2099, in orchestrate_task_run
    result = await call.aresult()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmpapkcmv_1prefect/producer.py", line 76, in collect_data
    data= list(pool.map(retrieve_real_time_data,*[divide_list(stock_symbols,num_of_thread),logger]))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
TypeError: 'PrefectLogAdapter' object is not iterable
12:33:40.424 | ERROR   | Task run 'collect_data-0' - Finished in state Failed("Task run encountered an exception TypeError: 'PrefectLogAdapter' object is not iterable")
12:33:40.438 | ERROR   | Flow run 'defiant-harrier' - Encountered exception during execution:
Traceback (most recent call last):
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 875, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmpapkcmv_1prefect/producer.py", line 102, in main
    data=collect_data()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/tasks.py", line 600, in __call__
    return enter_task_run_engine(
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 1417, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 1551, in get_task_call_return_value
    return await future._result()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/engine.py", line 2099, in orchestrate_task_run
    result = await call.aresult()
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/huythai/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmpapkcmv_1prefect/producer.py", line 76, in collect_data
    data= list(pool.map(retrieve_real_time_data,*[divide_list(stock_symbols,num_of_thread),logger]))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
TypeError: 'PrefectLogAdapter' object is not iterable
12:33:40.747 | ERROR   | Flow run 'defiant-harrier' - Finished in state Failed("Flow run encountered an exception. TypeError: 'PrefectLogAdapter' object is not iterable")
12:33:43.771 | INFO    | prefect.infrastructure.process - Process 'defiant-harrier' exited cleanly.
12:36:01.300 | INFO    | prefect.agent - Submitting flow run '162f1d57-7671-4c01-9b8f-71205547cbe0'
12:36:02.886 | INFO    | prefect.infrastructure.process - Opening process 'sensible-bullmastiff'...
12:36:03.196 | INFO    | prefect.agent - Completed submission of flow run '162f1d57-7671-4c01-9b8f-71205547cbe0'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
12:36:06.806 | INFO    | Flow run 'sensible-bullmastiff' - Downloading flow code from storage at '/home/huythai/final/test_producer'
12:36:08.697 | INFO    | Flow run 'sensible-bullmastiff' - Created task run 'collect_data-0' for task 'collect_data'
12:36:08.701 | INFO    | Flow run 'sensible-bullmastiff' - Executing 'collect_data-0' immediately...
12:36:56.426 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
12:38:15.345 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
12:38:44.762 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
12:38:45.108 | INFO    | Flow run 'sensible-bullmastiff' - Created task run 'transform_data-0' for task 'transform_data'
12:38:45.109 | INFO    | Flow run 'sensible-bullmastiff' - Executing 'transform_data-0' immediately...
12:38:46.250 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
12:38:46.550 | INFO    | Flow run 'sensible-bullmastiff' - Created task run 'load_data-0' for task 'load_data'
12:38:46.552 | INFO    | Flow run 'sensible-bullmastiff' - Executing 'load_data-0' immediately...
12:38:47.419 | INFO    | Task run 'load_data-0' - Finished in state Completed()
12:38:47.730 | INFO    | Flow run 'sensible-bullmastiff' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

12:38:50.860 | INFO    | prefect.infrastructure.process - Process 'sensible-bullmastiff' exited cleanly.
12:44:53.132 | INFO    | prefect.agent - Submitting flow run 'da6cd9d5-4bd0-4094-a2e0-fadb3a11ebed'
12:44:54.357 | INFO    | prefect.infrastructure.process - Opening process 'logical-lorikeet'...
12:44:54.725 | INFO    | prefect.agent - Completed submission of flow run 'da6cd9d5-4bd0-4094-a2e0-fadb3a11ebed'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
12:44:58.514 | INFO    | Flow run 'logical-lorikeet' - Downloading flow code from storage at '/home/huythai/final/test_producer'
12:45:00.464 | INFO    | Flow run 'logical-lorikeet' - Created task run 'collect_data-0' for task 'collect_data'
12:45:00.468 | INFO    | Flow run 'logical-lorikeet' - Executing 'collect_data-0' immediately...
12:45:45.121 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
12:47:01.765 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
12:47:31.117 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
12:47:31.431 | INFO    | Flow run 'logical-lorikeet' - Created task run 'transform_data-0' for task 'transform_data'
12:47:31.433 | INFO    | Flow run 'logical-lorikeet' - Executing 'transform_data-0' immediately...
12:47:32.318 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
12:47:32.622 | INFO    | Flow run 'logical-lorikeet' - Created task run 'load_data-0' for task 'load_data'
12:47:32.623 | INFO    | Flow run 'logical-lorikeet' - Executing 'load_data-0' immediately...
12:47:33.487 | INFO    | Task run 'load_data-0' - Finished in state Completed()
12:47:33.826 | INFO    | Flow run 'logical-lorikeet' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

12:47:36.791 | INFO    | prefect.infrastructure.process - Process 'logical-lorikeet' exited cleanly.
12:59:57.466 | INFO    | prefect.agent - Submitting flow run '635402e2-5619-49e0-95e7-b0be573ae029'
12:59:59.100 | INFO    | prefect.infrastructure.process - Opening process 'lilac-silkworm'...
12:59:59.491 | INFO    | prefect.agent - Completed submission of flow run '635402e2-5619-49e0-95e7-b0be573ae029'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
13:00:06.503 | INFO    | Flow run 'lilac-silkworm' - Downloading flow code from storage at '/home/huythai/final/test_producer'
13:00:08.981 | INFO    | Flow run 'lilac-silkworm' - Created task run 'collect_data-0' for task 'collect_data'
13:00:08.983 | INFO    | Flow run 'lilac-silkworm' - Executing 'collect_data-0' immediately...
13:00:51.997 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
13:02:24.041 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
13:02:57.076 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
13:02:57.394 | INFO    | Flow run 'lilac-silkworm' - Created task run 'transform_data-0' for task 'transform_data'
13:02:57.397 | INFO    | Flow run 'lilac-silkworm' - Executing 'transform_data-0' immediately...
13:02:58.289 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
13:02:58.603 | INFO    | Flow run 'lilac-silkworm' - Created task run 'load_data-0' for task 'load_data'
13:02:58.606 | INFO    | Flow run 'lilac-silkworm' - Executing 'load_data-0' immediately...
13:02:59.478 | INFO    | Task run 'load_data-0' - Finished in state Completed()
13:02:59.809 | INFO    | Flow run 'lilac-silkworm' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

13:03:02.955 | INFO    | prefect.infrastructure.process - Process 'lilac-silkworm' exited cleanly.
13:14:54.015 | INFO    | prefect.agent - Submitting flow run '08149fd4-90a7-44df-827e-313ac36f6f79'
13:14:55.255 | INFO    | prefect.infrastructure.process - Opening process 'ambrosial-agama'...
13:14:55.588 | INFO    | prefect.agent - Completed submission of flow run '08149fd4-90a7-44df-827e-313ac36f6f79'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
13:14:59.127 | INFO    | Flow run 'ambrosial-agama' - Downloading flow code from storage at '/home/huythai/final/test_producer'
13:15:00.965 | INFO    | Flow run 'ambrosial-agama' - Created task run 'collect_data-0' for task 'collect_data'
13:15:00.967 | INFO    | Flow run 'ambrosial-agama' - Executing 'collect_data-0' immediately...
13:15:55.749 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
13:17:11.770 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
13:17:41.341 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
13:17:41.648 | INFO    | Flow run 'ambrosial-agama' - Created task run 'transform_data-0' for task 'transform_data'
13:17:41.649 | INFO    | Flow run 'ambrosial-agama' - Executing 'transform_data-0' immediately...
13:17:42.569 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
13:17:42.873 | INFO    | Flow run 'ambrosial-agama' - Created task run 'load_data-0' for task 'load_data'
13:17:42.875 | INFO    | Flow run 'ambrosial-agama' - Executing 'load_data-0' immediately...
13:17:46.319 | INFO    | Task run 'load_data-0' - Finished in state Completed()
13:17:46.643 | INFO    | Flow run 'ambrosial-agama' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

13:17:49.834 | INFO    | prefect.infrastructure.process - Process 'ambrosial-agama' exited cleanly.
13:29:46.490 | INFO    | prefect.agent - Submitting flow run '32fb3b53-805f-4ae8-b168-7cba0bbbe53c'
13:29:47.686 | INFO    | prefect.infrastructure.process - Opening process 'naughty-clam'...
13:29:47.999 | INFO    | prefect.agent - Completed submission of flow run '32fb3b53-805f-4ae8-b168-7cba0bbbe53c'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
13:29:51.374 | INFO    | Flow run 'naughty-clam' - Downloading flow code from storage at '/home/huythai/final/test_producer'
13:30:00.637 | INFO    | Flow run 'naughty-clam' - Created task run 'collect_data-0' for task 'collect_data'
13:30:00.641 | INFO    | Flow run 'naughty-clam' - Executing 'collect_data-0' immediately...
13:30:44.806 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
13:32:25.250 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
13:33:07.622 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
13:33:07.926 | INFO    | Flow run 'naughty-clam' - Created task run 'transform_data-0' for task 'transform_data'
13:33:07.928 | INFO    | Flow run 'naughty-clam' - Executing 'transform_data-0' immediately...
13:33:08.876 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
13:33:09.180 | INFO    | Flow run 'naughty-clam' - Created task run 'load_data-0' for task 'load_data'
13:33:09.183 | INFO    | Flow run 'naughty-clam' - Executing 'load_data-0' immediately...
13:33:12.412 | INFO    | Task run 'load_data-0' - Finished in state Completed()
13:33:12.742 | INFO    | Flow run 'naughty-clam' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

13:33:16.036 | INFO    | prefect.infrastructure.process - Process 'naughty-clam' exited cleanly.
13:44:51.814 | INFO    | prefect.agent - Submitting flow run '7456ffb0-beac-4771-aba4-0c8212c8a3f1'
13:44:53.012 | INFO    | prefect.infrastructure.process - Opening process 'mutant-tamarin'...
13:44:53.335 | INFO    | prefect.agent - Completed submission of flow run '7456ffb0-beac-4771-aba4-0c8212c8a3f1'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
13:44:56.686 | INFO    | Flow run 'mutant-tamarin' - Downloading flow code from storage at '/home/huythai/final/test_producer'
13:45:00.910 | INFO    | Flow run 'mutant-tamarin' - Created task run 'collect_data-0' for task 'collect_data'
13:45:00.913 | INFO    | Flow run 'mutant-tamarin' - Executing 'collect_data-0' immediately...
13:45:38.867 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
13:46:52.929 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
13:47:21.985 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
13:47:22.318 | INFO    | Flow run 'mutant-tamarin' - Created task run 'transform_data-0' for task 'transform_data'
13:47:22.319 | INFO    | Flow run 'mutant-tamarin' - Executing 'transform_data-0' immediately...
13:47:23.217 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
13:47:23.542 | INFO    | Flow run 'mutant-tamarin' - Created task run 'load_data-0' for task 'load_data'
13:47:23.545 | INFO    | Flow run 'mutant-tamarin' - Executing 'load_data-0' immediately...
13:47:27.478 | INFO    | Task run 'load_data-0' - Finished in state Completed()
13:47:27.876 | INFO    | Flow run 'mutant-tamarin' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

13:47:31.146 | INFO    | prefect.infrastructure.process - Process 'mutant-tamarin' exited cleanly.
13:59:48.017 | INFO    | prefect.agent - Submitting flow run '1b8a5185-9aab-4c4b-98b7-a91e918959b3'
13:59:49.411 | INFO    | prefect.infrastructure.process - Opening process 'amaranth-bettong'...
13:59:49.765 | INFO    | prefect.agent - Completed submission of flow run '1b8a5185-9aab-4c4b-98b7-a91e918959b3'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
13:59:53.439 | INFO    | Flow run 'amaranth-bettong' - Downloading flow code from storage at '/home/huythai/final/test_producer'
14:00:00.841 | INFO    | Flow run 'amaranth-bettong' - Created task run 'collect_data-0' for task 'collect_data'
14:00:00.845 | INFO    | Flow run 'amaranth-bettong' - Executing 'collect_data-0' immediately...
14:00:43.886 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
14:02:14.606 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
14:02:46.386 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
14:02:46.811 | INFO    | Flow run 'amaranth-bettong' - Created task run 'transform_data-0' for task 'transform_data'
14:02:46.812 | INFO    | Flow run 'amaranth-bettong' - Executing 'transform_data-0' immediately...
14:02:48.020 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
14:02:48.420 | INFO    | Flow run 'amaranth-bettong' - Created task run 'load_data-0' for task 'load_data'
14:02:48.422 | INFO    | Flow run 'amaranth-bettong' - Executing 'load_data-0' immediately...
14:02:52.464 | INFO    | Task run 'load_data-0' - Finished in state Completed()
14:02:52.829 | INFO    | Flow run 'amaranth-bettong' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

14:02:55.771 | INFO    | prefect.infrastructure.process - Process 'amaranth-bettong' exited cleanly.
14:14:49.138 | INFO    | prefect.agent - Submitting flow run '04531a37-d297-44b5-b2d3-442819c2b071'
14:14:50.378 | INFO    | prefect.infrastructure.process - Opening process 'positive-nuthatch'...
14:14:50.756 | INFO    | prefect.agent - Completed submission of flow run '04531a37-d297-44b5-b2d3-442819c2b071'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
14:14:53.999 | INFO    | Flow run 'positive-nuthatch' - Downloading flow code from storage at '/home/huythai/final/test_producer'
14:15:01.503 | INFO    | Flow run 'positive-nuthatch' - Created task run 'collect_data-0' for task 'collect_data'
14:15:01.506 | INFO    | Flow run 'positive-nuthatch' - Executing 'collect_data-0' immediately...
14:15:43.991 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
14:17:01.956 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
14:17:32.980 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
14:17:33.306 | INFO    | Flow run 'positive-nuthatch' - Created task run 'transform_data-0' for task 'transform_data'
14:17:33.307 | INFO    | Flow run 'positive-nuthatch' - Executing 'transform_data-0' immediately...
14:17:34.219 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
14:17:34.536 | INFO    | Flow run 'positive-nuthatch' - Created task run 'load_data-0' for task 'load_data'
14:17:34.538 | INFO    | Flow run 'positive-nuthatch' - Executing 'load_data-0' immediately...
14:17:38.368 | INFO    | Task run 'load_data-0' - Finished in state Completed()
14:17:38.752 | INFO    | Flow run 'positive-nuthatch' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

14:17:41.898 | INFO    | prefect.infrastructure.process - Process 'positive-nuthatch' exited cleanly.
14:29:53.127 | INFO    | prefect.agent - Submitting flow run '35d89a3c-c96c-4229-966a-ecb0410118b0'
14:29:54.623 | INFO    | prefect.infrastructure.process - Opening process 'astute-pogona'...
14:29:54.940 | INFO    | prefect.agent - Completed submission of flow run '35d89a3c-c96c-4229-966a-ecb0410118b0'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
14:29:58.460 | INFO    | Flow run 'astute-pogona' - Downloading flow code from storage at '/home/huythai/final/test_producer'
14:30:00.431 | INFO    | Flow run 'astute-pogona' - Created task run 'collect_data-0' for task 'collect_data'
14:30:00.433 | INFO    | Flow run 'astute-pogona' - Executing 'collect_data-0' immediately...
14:30:37.206 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
14:32:05.665 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
14:32:31.151 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
14:32:31.505 | INFO    | Flow run 'astute-pogona' - Created task run 'transform_data-0' for task 'transform_data'
14:32:31.507 | INFO    | Flow run 'astute-pogona' - Executing 'transform_data-0' immediately...
14:32:32.680 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
14:32:33.007 | INFO    | Flow run 'astute-pogona' - Created task run 'load_data-0' for task 'load_data'
14:32:33.009 | INFO    | Flow run 'astute-pogona' - Executing 'load_data-0' immediately...
14:32:35.571 | INFO    | Task run 'load_data-0' - Finished in state Completed()
14:32:35.899 | INFO    | Flow run 'astute-pogona' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

14:32:39.010 | INFO    | prefect.infrastructure.process - Process 'astute-pogona' exited cleanly.
14:44:58.196 | INFO    | prefect.agent - Submitting flow run '69cf88de-31f7-4f1c-b6a6-02a5e3c312ae'
14:44:59.380 | INFO    | prefect.infrastructure.process - Opening process 'magenta-cicada'...
14:44:59.720 | INFO    | prefect.agent - Completed submission of flow run '69cf88de-31f7-4f1c-b6a6-02a5e3c312ae'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
14:45:03.094 | INFO    | Flow run 'magenta-cicada' - Downloading flow code from storage at '/home/huythai/final/test_producer'
14:45:05.042 | INFO    | Flow run 'magenta-cicada' - Created task run 'collect_data-0' for task 'collect_data'
14:45:05.045 | INFO    | Flow run 'magenta-cicada' - Executing 'collect_data-0' immediately...
14:45:44.066 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
14:46:59.673 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
14:47:33.957 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
14:47:34.291 | INFO    | Flow run 'magenta-cicada' - Created task run 'transform_data-0' for task 'transform_data'
14:47:34.294 | INFO    | Flow run 'magenta-cicada' - Executing 'transform_data-0' immediately...
14:47:35.242 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
14:47:35.544 | INFO    | Flow run 'magenta-cicada' - Created task run 'load_data-0' for task 'load_data'
14:47:35.546 | INFO    | Flow run 'magenta-cicada' - Executing 'load_data-0' immediately...
14:47:36.464 | INFO    | Task run 'load_data-0' - Finished in state Completed()
14:47:36.795 | INFO    | Flow run 'magenta-cicada' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

14:47:39.957 | INFO    | prefect.infrastructure.process - Process 'magenta-cicada' exited cleanly.
14:59:48.682 | INFO    | prefect.agent - Submitting flow run '6d818acb-dfc8-4f78-bce3-a8b1d288d3b5'
14:59:49.814 | INFO    | prefect.infrastructure.process - Opening process 'busy-tanuki'...
14:59:50.212 | INFO    | prefect.agent - Completed submission of flow run '6d818acb-dfc8-4f78-bce3-a8b1d288d3b5'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
14:59:53.973 | INFO    | Flow run 'busy-tanuki' - Downloading flow code from storage at '/home/huythai/final/test_producer'
15:00:03.177 | INFO    | Flow run 'busy-tanuki' - Created task run 'collect_data-0' for task 'collect_data'
15:00:03.180 | INFO    | Flow run 'busy-tanuki' - Executing 'collect_data-0' immediately...
15:00:41.333 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
15:02:08.660 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
15:02:38.723 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
15:02:39.914 | INFO    | Flow run 'busy-tanuki' - Created task run 'transform_data-0' for task 'transform_data'
15:02:39.916 | INFO    | Flow run 'busy-tanuki' - Executing 'transform_data-0' immediately...
15:02:43.301 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
15:02:44.187 | INFO    | Flow run 'busy-tanuki' - Created task run 'load_data-0' for task 'load_data'
15:02:44.190 | INFO    | Flow run 'busy-tanuki' - Executing 'load_data-0' immediately...
15:02:52.321 | INFO    | Task run 'load_data-0' - Finished in state Completed()
15:02:53.684 | INFO    | Flow run 'busy-tanuki' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

15:02:56.669 | INFO    | prefect.infrastructure.process - Process 'busy-tanuki' exited cleanly.
15:15:00.119 | INFO    | prefect.agent - Submitting flow run 'c14a192d-aa32-4ef3-a611-59fd8cb781bc'
15:15:01.390 | INFO    | prefect.infrastructure.process - Opening process 'vague-cuttlefish'...
15:15:02.192 | INFO    | prefect.agent - Completed submission of flow run 'c14a192d-aa32-4ef3-a611-59fd8cb781bc'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
15:15:05.787 | INFO    | Flow run 'vague-cuttlefish' - Downloading flow code from storage at '/home/huythai/final/test_producer'
15:15:08.252 | INFO    | Flow run 'vague-cuttlefish' - Created task run 'collect_data-0' for task 'collect_data'
15:15:08.254 | INFO    | Flow run 'vague-cuttlefish' - Executing 'collect_data-0' immediately...
15:15:47.198 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
15:17:09.516 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
15:17:32.429 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
15:17:32.738 | INFO    | Flow run 'vague-cuttlefish' - Created task run 'transform_data-0' for task 'transform_data'
15:17:32.741 | INFO    | Flow run 'vague-cuttlefish' - Executing 'transform_data-0' immediately...
15:17:33.667 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
15:17:33.968 | INFO    | Flow run 'vague-cuttlefish' - Created task run 'load_data-0' for task 'load_data'
15:17:33.970 | INFO    | Flow run 'vague-cuttlefish' - Executing 'load_data-0' immediately...
15:17:34.902 | INFO    | Task run 'load_data-0' - Finished in state Completed()
15:17:35.236 | INFO    | Flow run 'vague-cuttlefish' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

15:17:38.364 | INFO    | prefect.infrastructure.process - Process 'vague-cuttlefish' exited cleanly.
15:30:01.073 | INFO    | prefect.agent - Submitting flow run '4fcf4481-9e64-479f-9ec7-dd7f0ce64717'
15:30:03.755 | INFO    | prefect.infrastructure.process - Opening process 'sturdy-centipede'...
15:30:04.114 | INFO    | prefect.agent - Completed submission of flow run '4fcf4481-9e64-479f-9ec7-dd7f0ce64717'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
15:30:07.585 | INFO    | Flow run 'sturdy-centipede' - Downloading flow code from storage at '/home/huythai/final/test_producer'
15:30:09.505 | INFO    | Flow run 'sturdy-centipede' - Created task run 'collect_data-0' for task 'collect_data'
15:30:09.509 | INFO    | Flow run 'sturdy-centipede' - Executing 'collect_data-0' immediately...
15:30:49.840 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
15:32:10.239 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
15:32:37.625 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
15:32:37.935 | INFO    | Flow run 'sturdy-centipede' - Created task run 'transform_data-0' for task 'transform_data'
15:32:37.938 | INFO    | Flow run 'sturdy-centipede' - Executing 'transform_data-0' immediately...
15:32:38.885 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
15:32:39.182 | INFO    | Flow run 'sturdy-centipede' - Created task run 'load_data-0' for task 'load_data'
15:32:39.184 | INFO    | Flow run 'sturdy-centipede' - Executing 'load_data-0' immediately...
15:32:40.081 | INFO    | Task run 'load_data-0' - Finished in state Completed()
15:32:40.420 | INFO    | Flow run 'sturdy-centipede' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

15:32:43.375 | INFO    | prefect.infrastructure.process - Process 'sturdy-centipede' exited cleanly.
15:44:48.715 | INFO    | prefect.agent - Submitting flow run '1410b3ef-2465-4fe3-a149-dc6d3bef8292'
15:44:50.001 | INFO    | prefect.infrastructure.process - Opening process 'naughty-crane'...
15:44:50.340 | INFO    | prefect.agent - Completed submission of flow run '1410b3ef-2465-4fe3-a149-dc6d3bef8292'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
15:44:53.747 | INFO    | Flow run 'naughty-crane' - Downloading flow code from storage at '/home/huythai/final/test_producer'
15:45:00.912 | INFO    | Flow run 'naughty-crane' - Created task run 'collect_data-0' for task 'collect_data'
15:45:00.914 | INFO    | Flow run 'naughty-crane' - Executing 'collect_data-0' immediately...
15:45:35.951 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
15:46:47.844 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
15:47:14.998 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
15:47:15.310 | INFO    | Flow run 'naughty-crane' - Created task run 'transform_data-0' for task 'transform_data'
15:47:15.313 | INFO    | Flow run 'naughty-crane' - Executing 'transform_data-0' immediately...
15:47:16.197 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
15:47:16.509 | INFO    | Flow run 'naughty-crane' - Created task run 'load_data-0' for task 'load_data'
15:47:16.511 | INFO    | Flow run 'naughty-crane' - Executing 'load_data-0' immediately...
15:47:17.349 | INFO    | Task run 'load_data-0' - Finished in state Completed()
15:47:17.701 | INFO    | Flow run 'naughty-crane' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

15:47:20.643 | INFO    | prefect.infrastructure.process - Process 'naughty-crane' exited cleanly.
15:59:48.554 | INFO    | prefect.agent - Submitting flow run 'e4db483c-9cc6-4d17-af7d-efb15ae60d72'
15:59:49.727 | INFO    | prefect.infrastructure.process - Opening process 'invisible-ant'...
15:59:50.035 | INFO    | prefect.agent - Completed submission of flow run 'e4db483c-9cc6-4d17-af7d-efb15ae60d72'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
15:59:54.130 | INFO    | Flow run 'invisible-ant' - Downloading flow code from storage at '/home/huythai/final/test_producer'
16:00:01.419 | INFO    | Flow run 'invisible-ant' - Created task run 'collect_data-0' for task 'collect_data'
16:00:01.421 | INFO    | Flow run 'invisible-ant' - Executing 'collect_data-0' immediately...
16:00:37.746 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
16:02:02.581 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
16:02:25.573 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
16:02:25.936 | INFO    | Flow run 'invisible-ant' - Created task run 'transform_data-0' for task 'transform_data'
16:02:25.944 | INFO    | Flow run 'invisible-ant' - Executing 'transform_data-0' immediately...
16:02:26.934 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
16:02:27.257 | INFO    | Flow run 'invisible-ant' - Created task run 'load_data-0' for task 'load_data'
16:02:27.260 | INFO    | Flow run 'invisible-ant' - Executing 'load_data-0' immediately...
16:02:28.488 | INFO    | Task run 'load_data-0' - Finished in state Completed()
16:02:28.842 | INFO    | Flow run 'invisible-ant' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

16:02:31.841 | INFO    | prefect.infrastructure.process - Process 'invisible-ant' exited cleanly.
16:14:47.438 | INFO    | prefect.agent - Submitting flow run 'fa87f137-1775-44b2-a421-26b4c2f4393b'
16:14:48.588 | INFO    | prefect.infrastructure.process - Opening process 'cornflower-jerboa'...
16:14:48.903 | INFO    | prefect.agent - Completed submission of flow run 'fa87f137-1775-44b2-a421-26b4c2f4393b'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
16:14:52.800 | INFO    | Flow run 'cornflower-jerboa' - Downloading flow code from storage at '/home/huythai/final/test_producer'
16:15:01.022 | INFO    | Flow run 'cornflower-jerboa' - Created task run 'collect_data-0' for task 'collect_data'
16:15:01.025 | INFO    | Flow run 'cornflower-jerboa' - Executing 'collect_data-0' immediately...
16:15:36.088 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
16:16:58.215 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
16:17:21.976 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
16:17:22.288 | INFO    | Flow run 'cornflower-jerboa' - Created task run 'transform_data-0' for task 'transform_data'
16:17:22.290 | INFO    | Flow run 'cornflower-jerboa' - Executing 'transform_data-0' immediately...
16:17:23.270 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
16:17:23.582 | INFO    | Flow run 'cornflower-jerboa' - Created task run 'load_data-0' for task 'load_data'
16:17:23.584 | INFO    | Flow run 'cornflower-jerboa' - Executing 'load_data-0' immediately...
16:17:24.450 | INFO    | Task run 'load_data-0' - Finished in state Completed()
16:17:24.782 | INFO    | Flow run 'cornflower-jerboa' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

16:17:28.058 | INFO    | prefect.infrastructure.process - Process 'cornflower-jerboa' exited cleanly.
16:29:45.297 | INFO    | prefect.agent - Submitting flow run 'f95286b5-4f1a-4833-ae4d-e62c757b085f'
16:29:46.486 | INFO    | prefect.infrastructure.process - Opening process 'tunneling-fennec'...
16:29:46.803 | INFO    | prefect.agent - Completed submission of flow run 'f95286b5-4f1a-4833-ae4d-e62c757b085f'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
16:29:50.407 | INFO    | Flow run 'tunneling-fennec' - Downloading flow code from storage at '/home/huythai/final/test_producer'
16:30:00.865 | INFO    | Flow run 'tunneling-fennec' - Created task run 'collect_data-0' for task 'collect_data'
16:30:00.867 | INFO    | Flow run 'tunneling-fennec' - Executing 'collect_data-0' immediately...
16:30:35.604 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
16:31:56.130 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
16:32:25.029 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
16:32:26.103 | INFO    | Flow run 'tunneling-fennec' - Created task run 'transform_data-0' for task 'transform_data'
16:32:26.105 | INFO    | Flow run 'tunneling-fennec' - Executing 'transform_data-0' immediately...
16:32:27.786 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
16:32:28.097 | INFO    | Flow run 'tunneling-fennec' - Created task run 'load_data-0' for task 'load_data'
16:32:28.099 | INFO    | Flow run 'tunneling-fennec' - Executing 'load_data-0' immediately...
16:32:29.026 | INFO    | Task run 'load_data-0' - Finished in state Completed()
16:32:29.365 | INFO    | Flow run 'tunneling-fennec' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

16:32:32.527 | INFO    | prefect.infrastructure.process - Process 'tunneling-fennec' exited cleanly.
16:44:52.896 | INFO    | prefect.agent - Submitting flow run 'de692490-983b-4be2-97d9-1fff4cd67725'
16:44:54.246 | INFO    | prefect.infrastructure.process - Opening process 'deft-sparrow'...
16:44:54.576 | INFO    | prefect.agent - Completed submission of flow run 'de692490-983b-4be2-97d9-1fff4cd67725'
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
16:44:57.929 | INFO    | Flow run 'deft-sparrow' - Downloading flow code from storage at '/home/huythai/final/test_producer'
16:45:01.159 | INFO    | Flow run 'deft-sparrow' - Created task run 'collect_data-0' for task 'collect_data'
16:45:01.160 | INFO    | Flow run 'deft-sparrow' - Executing 'collect_data-0' immediately...
16:45:36.491 | ERROR   | root - Error processing stock symbol ROS: local variable 'df' referenced before assignment
16:46:57.363 | ERROR   | root - Error processing stock symbol TKC: local variable 'df' referenced before assignment
16:47:17.517 | INFO    | Task run 'collect_data-0' - Finished in state Completed()
16:47:17.845 | INFO    | Flow run 'deft-sparrow' - Created task run 'transform_data-0' for task 'transform_data'
16:47:17.847 | INFO    | Flow run 'deft-sparrow' - Executing 'transform_data-0' immediately...
16:47:18.706 | INFO    | Task run 'transform_data-0' - Finished in state Completed()
16:47:19.000 | INFO    | Flow run 'deft-sparrow' - Created task run 'load_data-0' for task 'load_data'
16:47:19.001 | INFO    | Flow run 'deft-sparrow' - Executing 'load_data-0' immediately...
16:47:19.867 | INFO    | Task run 'load_data-0' - Finished in state Completed()
16:47:20.227 | INFO    | Flow run 'deft-sparrow' - Finished in state Completed('All states completed.')
Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
 

16:47:23.406 | INFO    | prefect.infrastructure.process - Process 'deft-sparrow' exited cleanly.
